export default {
    en: {
        app: {
            name: 'KKF Domestic Sales',
            KKF: 'KHON KAEN FISHING NET FACTORY CO.,LTD. ',
            KIG: 'KKF International Group Co., Ltd.',
            AMW: 'Auto Motion Works Co., Ltd.',
            KKE: 'KK ENERGY RESOURCES CO., LTD.',
        },
        member: {
            welcomeTo: 'Welcome to',
        },
        dic: {
            sales: 'Sales',
            quotation: 'Quotation',
            manage: 'Manage',
            approve: 'Approve',
            report: 'Report',
            proformainvoice: 'Proforma Invoice',
            order: 'Order',
            setup: 'Setup',
            default: 'Default',
            authorization: 'Authorization',
            role: 'Role',
            tradeterm: 'TradeTerm',
            financial: 'Financial',
            paymenttype: 'Paymenttype',
            initial: 'Initial',
            country: 'Country',
            zone: 'Zone',
            filter: 'Filter',
            search: 'Search',
            add: 'Add',
            clone: 'Clone',
            edit: 'Edit',
            view: "View",
            delete: 'Delete',
            _no: 'No.',
            code: 'Code',
            description: 'Description',
            status: 'Status',
            lastupdate: 'Last Update',
            updateid: 'Update ID',
            nodata: 'No Data Available',
            show: 'Show',
            all: 'All',
            entries: 'entries',
            previous: 'Previous',
            next: 'Next',
            ok: 'Ok',
            save: 'Save',
            cancel: 'Cancel',
            msgdel: 'Confirm data deletion.',
            password: 'Password',
            username: 'Username',
            twofactor: '2 Factor',
            signin: 'Sign In',
            signup: 'Sign Up',
            resetpassword: 'Reset Password',
            confirm: 'Confirm',
            statusflag: 'Status Flag',
            grouptype: 'Group Type',
            approval: 'Approval',
            updateflag: 'Update Flag',
            approvalstep: 'Approval Step',
            step: 'Step',
            isapproved: 'Is Approved',
            actionflag: 'Action Flag',
            on: 'ON',
            off: 'OFF',
            yes: 'Yes',
            no: 'No',
            help: 'Help',
            textcolor: 'Text Color',
            currency: 'Currency',
            codecurrency: 'Code',
            roleapprovalstep: 'Role Approval Step',
            approvaldetail: 'Approval Detail',
            tradeterm: 'Trade Term',
            more: 'More',
            hide: 'Hide',
            codeold: 'Code Old',
            duedatetype: 'Due Date Type',
            businessstatus: 'Business Status',
            product: 'Product',
            packing: 'Packing',
            descriptionth: 'Description TH',
            picturefile: 'Picture File',
            production: 'production',
            closeworkorder: 'Close a Work Order',
            moveworkorder: 'Moving a Work Order',
            followsworkorder: 'follows a Work Order',
            barcodescanner: 'barcodescanner',
            shortcutworkorder: 'Shortcut a Work Order',
            rptdrawing: 'Report The Drawing',
            office: 'Office',
            company: 'Company',
            company_filter: 'Company filter',
            db: 'Database',
            signout: 'Log out',
            administrator: 'Function การทำงาน',
            workprocess: 'การตรวจสอบสิทธิ์การทำงาน',
            workprocessadmin: 'ผู้มีสิทธิ์การทำงาน',
            sequence: 'sequence',
            permission: 'กำหนดสิทธิ์การทำงาน',
            remark: 'Remark',
        }
    },
    th: {
        app: {
            name: 'ระบบขายในประเทศ KKF',
            KKF: 'บริษัท ขอนแก่นแหอวน จำกัด',
            KIG: 'บริษัท เคเคเอฟ อินเตอร์เนชั่นแนล กรุ๊ป จำกัด',
            AMW: 'บริษัท ออโต้โมชั่นเวิร์ค จำกัด',
            KKE: 'บริษัท เคเค เอ็นเนอร์จี รีซอร์สเซส จำกัด',
        },
        member: {
            welcomeTo: 'ยินดีต้อนรับ',
        },
        dic: {
            sales: 'ขาย',
            quotation: 'เสนอราคาขาย',
            manage: 'จัดการ',
            approve: 'อนุมัติ',
            report: 'รายงาน',
            proformainvoice: 'สัญญาชื้อขาย',
            order: 'ใบสั่งผลิต',
            setup: 'ตั้งค่าระบบ',
            default: 'ค่าเริ่มต้น',
            authorization: 'การระบุตัวตน',
            role: 'กลุ่มสิทธิ์',
            financial: 'การเงิน',
            paymenttype: 'ประเภทการชำระ',
            initial: 'ตั้งต้น',
            country: 'ประเทศ',
            zone: 'โซน',
            filter: 'กรองข้อมูล',
            search: 'ค้นหา',
            add: 'เพิ่ม',
            clone: 'โคลน',
            view: 'ดู',
            edit: 'แก้ไข',
            delete: 'ลบ',
            _no: 'เลขที่',
            code: 'รหัส',
            description: 'รายละเอียด',
            status: 'สถานะ',
            lastupdate: 'แก้ไขล่าสุด',
            updateid: 'ผู้แก้ไข',
            nodata: 'ไม่มีข้อมูล',
            show: 'แสดง',
            all: 'ทั้งหมด',
            entries: 'รายการ',
            previous: 'ก่อนหน้า',
            next: 'ต่อไป',
            ok: 'ตกลง',
            save: 'บันทึก',
            cancel: 'ยกเลิก',
            msgdel: 'ยืนยันการลบข้อมูล',
            password: 'รหัสผ่าน',
            username: 'Username',
            twofactor: 'รหัส 2 FA',
            signin: 'ลงชื่อเข้าใช้งาน',
            signup: 'สมัครสมาชิก',
            resetpassword: 'รีเซ็ตรหัสผ่าน',
            confirm: 'ยืนยัน',
            statusflag: 'แฟลกสถานะ',
            grouptype: 'ประเภทกลุ่ม',
            approval: 'การอนุมัติ',
            updateflag: 'การเปลี่ยนแปลง',
            approvalstep: 'ขั้นตอนการอนุมัติ',
            step: 'ขั้นตอน',
            isapproved: 'ได้รับการอนุมัติ',
            actionflag: 'การกระทำ',
            on: 'เปิด',
            off: 'ปิด',
            yes: 'ใช่',
            no: 'ไม่ใช่',
            help: 'ช่วยเหลือ',
            textcolor: 'สีตัวอักษร',
            currency: 'สกุลเงิน',
            codecurrency: 'สกุลเงิน',
            roleapprovalstep: 'กลุ่มสิทธิ์การอนุมัติ',
            approvaldetail: 'รายละเอียดการอนุมัติ',
            tradeterm: 'ประเภทเสนอราคา',
            more: 'เพิ่มเติม',
            hide: 'ซ่อน',
            codeold: 'รหัสเก่า',
            duedatetype: 'ประเภท Due Date',
            businessstatus: 'สถานะทางธุรกิจ',
            product: 'สินค้า',
            packing: 'การบรรจุ',
            descriptionth: 'รายละเอียดไทย',
            picturefile: 'ไฟล์รูปภาพ',
            production: 'การผลิต',
            closeworkorder: 'บันทึกยิงปิดงานใบสั่งผลิต',
            moveworkorder: 'บันทึกยิงย้ายงานไป สถานีงานถัดไป ',
            followsworkorder: 'การติดตามสถานะใบสั่งผลิต',
            barcodescanner: 'barcodescanner',
            shortcutworkorder: 'คียลัด ยิงปิด/ย้าย ใบสั่งผลิต',
            rptdrawing: 'แสดงแบบการผลิต',
            office: 'สาขา',
            company: 'บริษัท',
            company_filter: 'แสดงข้อมูลของบริษัท',
            db: 'ฐานข้อมูล',
            signout: 'ออกจากระบบ',
            administrator: 'Function การทำงาน',
            workprocess: 'การตรวจสอบสิทธิ์การทำงาน',
            workprocessadmin: 'ผู้มีสิทธิ์การทำงาน',
            sequence: 'ลำดับ',
            permission: 'กำหนดสิทธิ์การทำงาน',
            remark: 'ผู้รับผิดชอบ',
            permission_help: 'Click ที่แถว เพื่อแสดงรายละเอียดข้อมูล',
        }
    }
}